name: Deploy to Vercel

on:
  push:
    branches:
      - '**'  # Trigger on all branches

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Vercel deployment mode
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "VERCEL_ARGS=--prod" >> $GITHUB_ENV
          else
            echo "VERCEL_ARGS=" >> $GITHUB_ENV
          fi

      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: ${{ env.VERCEL_ARGS }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
